version: '3.8'

services:
    db:
        image: postgres
        restart: unless-stopped # We don't want this to run indefinitely
        env_file:
            - .env # Centralize .env variables from an external file
        volumes:
            - psql:/var/lib/postgresql/data
        ports:
            - 5432:5432
volumes:
    psql:
